// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int64            `json:"id"`
	Login     string           `json:"login"`
	PwdHash   string           `json:"pwd_hash"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
